name: Deploy to Modal

on:
    push:
        branches: [main]
        paths:
          - 'main.py' #trigger only if this file changes
    workflow_dispatch: #keeps manual trigger available anytime

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4


            - name: Set up python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
              
            - name: Cache pip
              uses: actions/cache@v3
              with:
                path: ~/.cache/pip
                key: ${{runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-pip-


            - name: Install Modal
              run: pip install modal

            - name: Deploy 10k Checkboxes app
              env:
                MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }} 
                MODAL_TOKEN_SECRET:  ${{ secrets.MODAL_TOKEN_SECRET }} 

              run: |
                pip install python-fasthtml==0.12.36 httpx==0.27.0 redis>=5.3.0 pytz aiosqlite markdown==3.10.2
                modal deploy main.py --name fasthtml-checkboxes

